### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by REPTILEHAUS** [backand/backand-ionic2-starter#2]
Tried to get the starter going but keep running into compilation issues below:

```
        [17:05:13]  ionic-app-scripts 0.0.27
        [17:05:13]  watch started ...
        [17:05:13]  build dev started ...
        [17:05:13]  clean started ...
        [17:05:13]  clean finished in 45 ms
        [17:05:13]  copy started ...
        [17:05:13]  typescript compiler started ...
        [17:05:13]  lint started ...
        [17:05:14]  copy finished in 749 ms
        [17:05:17]  lint finished in 3.53 s
        [17:05:18]  src/app/main.dev.ts(3,27): error TS2307: Cannot find module './app.module'.
        [17:05:18]  typescript compiler ready in 5.12 s
        [17:05:18]  bundle dev started ...
        [17:05:18]  Error: Could not resolve entry (./.tmp/app/main.dev.js)
            at /Applications/MAMP/htdocs/projects/myApp/node_modules/rollup/dist/rollup.js:8602:28
            at process._tickCallback (node.js:369:9)

        [17:05:18]  sass started ...
        [17:05:18]  sass failed:  Cannot generate Sass files without first bundling JavaScript files in order to know all used modules. Please build JS files first.

        [17:05:18]  build dev failed:  Build failed

        [17:05:18]  Missing module paths for sass build
```

npm -v = 3.10.8
ionic -v = 2.1.0

Also just noticed that its looking for this file /.tmp/app/main.dev.js however it does exist but just not within the app folder, its sitting here  /.tmp/main.dev.js

**Comment by kornatzky** [comment]
We have built the app with Ionic 2 but a version prior to the RC released a few days ago. We have upgraded our ionic and reproduced the issue. We are now working on updating the starter for Ionic 2 RC. A new version will be released soon.
