### ISSUE TITLE
ionic serve cannot find module parseuri. not sure what is going on

### ISSUE THREAD

**Issue by crossiono** [backand/backand-ionic2-starter#6]
Error: Cannot find module "parseuri"
    at webpackMissingModule (http://localhost:8100/build/main.js:124598:80)
    at Object.<anonymous> (http://localhost:8100/build/main.js:124598:165)
    at Object.<anonymous> (http://localhost:8100/build/main.js:124669:30)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:124483:11)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:18737:75)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:58753:84)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
Ionic Framework: 2.0.0-rc.5
Ionic Native: 2.2.11
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.2
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by kornatzky** [comment]
Not reproduced when using:
 ionic serve
ionic version 2.1.17
cordova version 6.4.0

**Comment by m4eXtr0m4** [comment]
check this thread...https://stackoverflow.com/questions/25360313/cannot-find-module-parseuri

**Comment by kornatzky** [comment]
Not reproduced. Make sure you download the latest. Because I just committed a change to index.html.

My setup: 

ionic 3.19.0
node 9.3.0
npm 5.6.0
cordova 8.0.0


Your `index.html` should include this line:
`<script src="build/vendor.js"></script>`
Like: 

     <body>

    
    <ion-app></ion-app>

    
    <script src="cordova.js"></script>

    
    <script src="build/polyfills.js"></script>
    
    
    <script src="build/vendor.js"></script>

    
    <script src="build/main.js"></script>

    </body>

Install all dependencies. Including those for Facebook, Google, and Facebook web app.
